apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: contact@zeet.co
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
      - selector:
          matchLabels:
            use-dns-challenge: "true"
        dns01:
          cnameStrategy: Follow
          webhook:
            solverName: linode
            groupName: acme.slicen.me
---
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: linode-credentials
data:
  token: ${LINODE_TOKEN_B64}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeet-app-cert
  namespace: traefik
  labels:
    use-dns-challenge: "true"
spec:
  dnsNames:
    - "${CLUSTER_DOMAIN}"
    - "*.${CLUSTER_DOMAIN}"
  secretName: zeet-app-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: zeet-app-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ssl-redirect
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: zeet-auth
  namespace: traefik
spec:
  basicAuth:
    secret: zeet-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: zeet-auth
  namespace: traefik
data:
  users: ${PROMETHEUS_AUTH}
